import alchemy from "alchemy";
import { Buffer } from "node:buffer";
import { mkdir } from "node:fs/promises";
import { R2RestStateStore } from "alchemy/state";
import {
  CloudflareApiError,
  DurableObjectNamespace,
  KVNamespace,
  R2Bucket,
  Worker,
  createBucket,
  createCloudflareApi,
  getBucket,
} from "alchemy/cloudflare";

function requireEnv(name: string): string {
  const value = process.env[name]?.trim();

  if (!value) {
    throw new Error(`${name} is required for cinder provisioning`);
  }

  return value;
}

const githubPat = requireEnv("GITHUB_PAT");
const webhookSecret = requireEnv("GITHUB_WEBHOOK_SECRET");
const internalToken = requireEnv("CINDER_INTERNAL_TOKEN");
const fixtureRepo = process.env.CINDER_FIXTURE_REPO?.trim() || "acoyfellow/cinder-prd-test";
const fixtureBranch = process.env.CINDER_FIXTURE_BRANCH?.trim() || "main";
const fixtureWorkflow =
  process.env.CINDER_FIXTURE_WORKFLOW?.trim() || "cinder-proof.yml";
const githubApiBase = "https://api.github.com";
const stateBucketName = process.env.CINDER_STATE_BUCKET?.trim();
const stateBucketRegion = process.env.CINDER_STATE_REGION?.trim() || "auto";

const fixtureCargoToml = `[package]
name = "cinder-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`;

const fixtureCargoLock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "cinder-proof"
version = "0.1.0"
dependencies = [
 "serde",
 "serde_json",
]

[[package]]
name = "itoa"
version = "1.0.17"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "92ecc6618181def0457392ccd0ee51198e065e016d1d527a7ac1b6dc7c1f09d2"

[[package]]
name = "memchr"
version = "2.8.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "f8ca58f447f06ed17d5fc4043ce1b10dd205e060fb3ce5b979b8ed8e59ff3f79"

[[package]]
name = "proc-macro2"
version = "1.0.106"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8fd00f0bb2e90d81d1044c2b32617f68fcb9fa3bb7640c23e9c748e53fb30934"
dependencies = [
 "unicode-ident",
]

[[package]]
name = "quote"
version = "1.0.44"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "21b2ebcf727b7760c461f091f9f0f539b77b8e87f2fd88131e7f1b433b3cece4"
dependencies = [
 "proc-macro2",
]

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "9a8e94ea7f378bd32cbbd37198a4a91436180c5bb472411e48b5ec2e2124ae9e"
dependencies = [
 "serde_core",
 "serde_derive",
]

[[package]]
name = "serde_core"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "41d385c7d4ca58e59fc732af25c3983b67ac852c1a25000afe1175de458b67ad"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "d540f220d3187173da220f885ab66608367b6574e925011a9353e4badda91d79"
dependencies = [
 "proc-macro2",
 "quote",
 "syn",
]

[[package]]
name = "serde_json"
version = "1.0.149"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "83fc039473c5595ace860d8c4fafa220ff474b3fc6bfdb4293327f1a37e94d86"
dependencies = [
 "itoa",
 "memchr",
 "serde",
 "serde_core",
 "zmij",
]

[[package]]
name = "syn"
version = "2.0.117"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "e665b8803e7b1d2a727f4023456bbbbe74da67099c585258af0ad9c5013b9b99"
dependencies = [
 "proc-macro2",
 "quote",
 "unicode-ident",
]

[[package]]
name = "unicode-ident"
version = "1.0.24"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "e6e4313cd5fcd3dad5cafa179702e2b244f760991f45397d14d4ebf38247da75"

[[package]]
name = "zmij"
version = "1.0.21"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b8848ee67ecc8aedbaf3e4122217aff892639231befc6a1b58d29fff4c2cabaa"
`;

const fixtureMainRs = `use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
struct ProofMessage {
    ok: bool,
    source: &'static str,
}

fn main() {
    let message = ProofMessage {
        ok: true,
        source: "cinder-proof",
    };

    println!("{}", serde_json::to_string(&message).unwrap());
}
`;

const fixtureWorkflowContents = `name: cinder-proof
on:
  workflow_dispatch:
jobs:
  cargo-build:
    runs-on: [self-hosted, cinder]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Build fixture
        run: cargo build --locked
      - name: Run fixture
        run: cargo run --locked
`;

function parseFixtureRepository(repoRef: string) {
  const [owner, name, ...extra] = repoRef.split("/");

  if (!owner || !name || extra.length > 0) {
    throw new Error(
      `CINDER_FIXTURE_REPO must be "owner/name" but received "${repoRef}"`,
    );
  }

  return { owner, name };
}

async function githubRequest(
  path: string,
  init: RequestInit = {},
  okStatuses: number[] = [200],
) {
  const response = await fetch(`${githubApiBase}${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${githubPat}`,
      "User-Agent": "cinder-provisioner",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init.headers ?? {}),
    },
  });

  if (okStatuses.includes(response.status)) {
    return response;
  }

  const body = await response.text();
  throw new Error(
    `GitHub API ${init.method ?? "GET"} ${path} failed with ${response.status}: ${body}`,
  );
}

async function ensureFixtureRepository() {
  const { owner, name } = parseFixtureRepository(fixtureRepo);
  const existing = await githubRequest(`/repos/${owner}/${name}`, {}, [200, 404]);

  if (existing.status === 200) {
    return (await existing.json()) as { default_branch: string; full_name: string };
  }

  const viewer = (await (
    await githubRequest("/user")
  ).json()) as { login: string };

  if (viewer.login !== owner) {
    throw new Error(
      `Fixture repo ${fixtureRepo} is missing and cannot be auto-created because PAT owner "${viewer.login}" does not match "${owner}"`,
    );
  }

  const created = await githubRequest(
    "/user/repos",
    {
      method: "POST",
      body: JSON.stringify({
        name,
        description: "Canonical GitHub proof fixture for Cinder",
        auto_init: true,
        private: false,
      }),
    },
    [201],
  );

  return (await created.json()) as { default_branch: string; full_name: string };
}

async function ensureFixtureBranch(repo: { default_branch: string }) {
  if (fixtureBranch === repo.default_branch) {
    return;
  }

  const { owner, name } = parseFixtureRepository(fixtureRepo);
  const branchResponse = await githubRequest(
    `/repos/${owner}/${name}/git/ref/heads/${encodeURIComponent(fixtureBranch)}`,
    {},
    [200, 404],
  );

  if (branchResponse.status === 200) {
    return;
  }

  const defaultBranchRef = (await (
    await githubRequest(
      `/repos/${owner}/${name}/git/ref/heads/${encodeURIComponent(repo.default_branch)}`,
    )
  ).json()) as { object: { sha: string } };

  await githubRequest(
    `/repos/${owner}/${name}/git/refs`,
    {
      method: "POST",
      body: JSON.stringify({
        ref: `refs/heads/${fixtureBranch}`,
        sha: defaultBranchRef.object.sha,
      }),
    },
    [201],
  );
}

async function upsertFixtureFile(path: string, content: string, message: string) {
  const { owner, name } = parseFixtureRepository(fixtureRepo);
  const encodedPath = path
    .split("/")
    .map((segment) => encodeURIComponent(segment))
    .join("/");
  const existing = await githubRequest(
    `/repos/${owner}/${name}/contents/${encodedPath}?ref=${encodeURIComponent(fixtureBranch)}`,
    {},
    [200, 404],
  );
  const sha =
    existing.status === 200
      ? ((await existing.json()) as { sha: string }).sha
      : undefined;

  await githubRequest(
    `/repos/${owner}/${name}/contents/${encodedPath}`,
    {
      method: "PUT",
      body: JSON.stringify({
        message,
        branch: fixtureBranch,
        content: Buffer.from(content, "utf8").toString("base64"),
        sha,
      }),
    },
    [200, 201],
  );
}

async function upsertFixtureWebhook(webhookUrl: string) {
  const { owner, name } = parseFixtureRepository(fixtureRepo);
  const hooks = (await (
    await githubRequest(`/repos/${owner}/${name}/hooks`)
  ).json()) as Array<{ id: number; name: string; config?: { url?: string } }>;
  const existing = hooks.find(
    (hook) => hook.name === "web" && hook.config?.url === webhookUrl,
  );
  const body = JSON.stringify({
    active: true,
    events: ["workflow_job"],
    config: {
      url: webhookUrl,
      content_type: "json",
      insecure_ssl: "0",
      secret: webhookSecret,
    },
  });

  if (existing) {
    await githubRequest(
      `/repos/${owner}/${name}/hooks/${existing.id}`,
      {
        method: "PATCH",
        body,
      },
      [200],
    );
    return;
  }

  await githubRequest(
    `/repos/${owner}/${name}/hooks`,
    {
      method: "POST",
      body,
    },
    [201],
  );
}

async function syncFixtureRepository(webhookUrl: string) {
  const repo = await ensureFixtureRepository();
  await ensureFixtureBranch(repo);

  await upsertFixtureFile("Cargo.toml", fixtureCargoToml, "chore: sync cinder fixture Cargo.toml");
  await upsertFixtureFile("Cargo.lock", fixtureCargoLock, "chore: sync cinder fixture Cargo.lock");
  await upsertFixtureFile("src/main.rs", fixtureMainRs, "chore: sync cinder fixture main.rs");
  await upsertFixtureFile(
    `.github/workflows/${fixtureWorkflow}`,
    fixtureWorkflowContents,
    "chore: sync cinder fixture workflow",
  );
  await upsertFixtureWebhook(webhookUrl);
}

async function ensureStateBucket(bucketName: string, locationHint: string) {
  const accountId = requireEnv("CLOUDFLARE_ACCOUNT_ID");
  const apiToken = requireEnv("CLOUDFLARE_API_TOKEN");
  const api = await createCloudflareApi({ accountId, apiToken } as any);

  try {
    await getBucket(api, bucketName);
    return { accountId, apiToken };
  } catch (error) {
    if (!(error instanceof CloudflareApiError) || error.status !== 404) {
      throw error;
    }
  }

  await createBucket(api, bucketName, { locationHint });
  return { accountId, apiToken };
}

const stateStoreCredentials = stateBucketName
  ? await ensureStateBucket(stateBucketName, stateBucketRegion)
  : null;

export const app = await alchemy("cinder", {
  stage: process.env.CINDER_STAGE ?? "production",
  ...(stateBucketName && stateStoreCredentials
    ? {
        stateStore: (scope) =>
          new R2RestStateStore(scope, {
            accountId: stateStoreCredentials.accountId,
            apiToken: stateStoreCredentials.apiToken,
            bucketName: stateBucketName,
          } as any),
      }
    : {}),
});

export const cacheBucket = await R2Bucket("cinder-cache", {
  empty: false,
});

export const runnerState = await KVNamespace("cinder-runner-state");

export const runnerPool = await DurableObjectNamespace("RunnerPool", {
  className: "RunnerPool",
  sqlite: true,
});

export const jobQueue = await DurableObjectNamespace("JobQueue", {
  className: "JobQueue",
  sqlite: true,
});

export const cacheWorker = await Worker("cinder-cache-worker", {
  entrypoint: "./crates/cinder-cache/build/worker/shim.mjs",
  bindings: {
    CACHE_BUCKET: cacheBucket,
    CINDER_INTERNAL_TOKEN: alchemy.secret(internalToken),
  },
});

export const orchestrator = await Worker("cinder-orchestrator", {
  entrypoint: "./crates/cinder-orchestrator/build/worker/shim.mjs",
  bindings: {
    CACHE_BUCKET: cacheBucket,
    RUNNER_STATE: runnerState,
    RUNNER_POOL: runnerPool,
    JOB_QUEUE: jobQueue,
    GITHUB_WEBHOOK_SECRET: alchemy.secret(webhookSecret),
    CINDER_INTERNAL_TOKEN: alchemy.secret(internalToken),
    GITHUB_PAT: alchemy.secret(githubPat),
    CINDER_CACHE_WORKER_URL: cacheWorker.url!,
    CINDER_FIXTURE_REPO: fixtureRepo,
    CINDER_FIXTURE_BRANCH: fixtureBranch,
    CINDER_FIXTURE_WORKFLOW: fixtureWorkflow,
  },
});

await app.finalize();
await syncFixtureRepository(`${orchestrator.url}/webhook/github`);

const runtimeDirectory = new URL("./.gateproof/", import.meta.url);
const runtimeFile = new URL("./.gateproof/runtime.json", import.meta.url);

await mkdir(runtimeDirectory, { recursive: true });

await Bun.write(
  runtimeFile,
  `${JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      stage: process.env.CINDER_STAGE ?? "production",
      orchestratorName: orchestrator.name,
      orchestratorUrl: orchestrator.url,
      cacheWorkerName: cacheWorker.name,
      cacheWorkerUrl: cacheWorker.url,
      fixtureRepo,
      fixtureBranch,
      fixtureWorkflow,
    },
    null,
    2,
  )}\n`,
);

console.log(`Wrote runtime outputs to ${runtimeFile.pathname}`);
